# Generated by Django 3.0.5 on 2020-05-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=8)),
                ('farm_name', models.CharField(max_length=50)),
                ('farm_description', models.TextField()),
                ('farm_products', models.TextField()),
                ('farm_photo', models.ImageField(blank=True, upload_to='farmers/')),
                ('went_public', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('not public', 'Not Public'), ('public', 'Public')], default='not public', max_length=10)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-went_public',),
            },
            managers=[
                ('is_public', django.db.models.manager.Manager()),
            ],
        ),
    ]
