# Generated by Django 3.0.5 on 2020-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200428_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_city',
            field=models.CharField(default='hometown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_state',
            field=models.CharField(default='City', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_street',
            field=models.CharField(default='123 farm st', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_zipcode',
            field=models.CharField(default='123456', max_length=8),
            preserve_default=False,
        ),
    ]
