# Generated by Django 3.0.5 on 2020-05-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20200513_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=8)),
                ('farm_name', models.CharField(max_length=50)),
                ('farm_description', models.TextField()),
                ('farm_products', models.TextField()),
                ('farm_photo', models.ImageField(blank=True, upload_to='farmers/')),
                ('went_public', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('not public', 'Not Public'), ('public', 'Public')], default='not public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-went_public',),
            },
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
