# Generated by Django 3.0.5 on 2020-05-13 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200513_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='FarmerProfile',
        ),
    ]
