# Generated by Django 3.0.5 on 2020-05-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200503_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_photo',
            field=models.ImageField(blank=True, upload_to='farmers/'),
        ),
    ]
