# Generated by Django 3.0.5 on 2020-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200504_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(default='Farm Name', max_length=50),
            preserve_default=False,
        ),
    ]
