# Generated by Django 3.0.5 on 2020-05-07 02:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200506_1818'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmerprofile',
            managers=[
                ('is_public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='slug',
        ),
    ]
